##########################################################################
#
#  INFIVERVE TECHNOLOGIES PTE LIMITED CONFIDENTIAL
#  __________________
# 
#  (C) INFIVERVE TECHNOLOGIES PTE LIMITED, SINGAPORE
#  All Rights Reserved.
#  Product / Project: Flint IT Automation Platform
#  NOTICE:  All information contained herein is, and remains
#  the property of INFIVERVE TECHNOLOGIES PTE LIMITED.
#  The intellectual and technical concepts contained
#  herein are proprietary to INFIVERVE TECHNOLOGIES PTE LIMITED.
#  Dissemination of this information or any form of reproduction of this material
#  is strictly forbidden unless prior written permission is obtained
#  from INFIVERVE TECHNOLOGIES PTE LIMITED, SINGAPORE.

---
title: "Ifconfig"
description: "Gives configuration of the remote server"

flintbit: "flint-util:ssh:operation:ifconfig.rb"
icon: "fa fa-info"
inputs:
  -
    section: Basic Fields
    fields:
      -
        default:
        id: target
        label: Target
        placeholder: "Hostname of SSH-Server"
        type: textbox
        required: true
      -
        default:
        id: username
        label: Username
        placeholder: "Username of SSH-Server"
        type: textbox
        required: true
      -
        default:
        id: password
        label: Password
        placeholder: "Password of SSH-Server"
        type: password
        required: false
      -
        default:
        id: key-file
        label: Key
        placeholder: "Provide ssh key-file absolute path"
        type: textbox
        required: false
      -
        default:
        id: type
        label: Action Type
        options:
          - "exec"
          - "shell"
        placeholder: "Action to perform"
        type: select
        required: true
...
